freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y qjail
  networking_script:
    - ifconfig vtnet1 create
    - ifconfig -a
    - ifconfig vtnet1 192.168.0.254/24 up
  qjail_script:
    - ifconfig
    - qjail install
    - qjail create -4 192.168.0.2 jail1
    - qjail config -w vtnet1 -v ipfw jail1
  script:
    - qjail list
    - qjail start jail1
    - qjail console jail1
    - ifconfig -a
    - ipfw list
    - exit
