freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y python37
    - sysrc firewall_enable=YES
    - echo 'firewall_type="open"' >> /etc/rc.conf
    - echo 'firewall_script="/etc/rc.firewall"' >> /etc/rc.conf
    - kldload ipfw
    - echo 'ipfw add 100 allow all from any to any' >> /etc/rc.firewall
    - service ipfw start

  script:
    - ipfw list
    - python3.7 tests/test_ipfw.py
