freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y qjail
  networking_script:
    - sysrc gateway_enable=YES
    - sysctl net.inet.ip.forwarding=1
    - sysctl security.jail.allow_raw_sockets=1
    - kldload ipfw ; sysctl net.inet.ip.fw.enable=0
    - ifconfig bridge create
    - ifconfig bridge0 192.168.0.1/24 up
    - ifconfig epair create
    - ifconfig epair create
    - ifconfig
    - ifconfig epair1b up
    - ifconfig bridge0 addm epair1b addm vtnet0
    - cat /etc/resolv.conf
  qjail_script:
    - ifconfig
    - qjail install -h ftp3.jp.freebsd.org
    - qjail create -n lo0 -4 127.0.0.1 jail1
    - cat /usr/local/etc/qjail.config/jail1
    - cp jail_setting.txt /usr/local/etc/qjail.config/jail1
    - qjail start jail1
    - netstat -rn
    - ifconfig
    - ping -c 4 192.168.0.2
    - jexec jail1 ifconfig
    - jexec jail1 echo 'search c.cirrus-ci-community.internal google.internal' > /etc/resolv.conf
    - jexec jail1 echo 'nameserver 169.254.169.254' >> /etc/resolv.conf
    - jexec jail1 cat /etc/resolv.conf
    - jexec jail1 sysrc firewall_enable=YES
    - jexec jail1 echo 'firewall_type="open"' >> /etc/rc.conf
    - jexec jail1 service ipfw start
    - jexec jail1 ipfw zero
    - jexec jail1 ipfw add 10 allow all from any to any
    - jexec jail1 ipfw list
    - jexec jail1 pkg update
    - jexec jail1 pkg install -y git
