freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y qjail
  networking_script:
    - sysctl net.inet.ip.forwarding=1
    - ifconfig bridge create
    - ifconfig bridge0 192.168.0.1/24 up
    - ifconfig epair create
    - ifconfig epair0b up
    - ifconfig bridge0 addm epair0b
    - ifconfig epair0a 192.168.0.254/24 up
  qjail_script:
    - ifconfig epair create
    - ifconfig epair1b up
    - ifconfig bridge0 addm epair1b
    - qjail install
    - qjail create -n lo0 -4 127.0.0.1 jail1
    - cp jail_setting.txt /usr/local/etc/qjail.config/jail
    - qjail start jail1
    - ifconfig -a
  script:
    - qjail console jail1
    - ifconfig -a
    - ipfw list
    - exit
