freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y python37
    - sysrc firewall_enable=YES
    - echo '${fwcmd} add 1100 allow tcp from any to any' >> /etc/rc.firewall
    - service ipfw restart

  script:
    - python3.7 tests/test_ipfw_list.py
