freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y qjail
  networking_script:
    - sysctl net.inet.ip.forwarding=1
    - ifconfig bridge create
    - ifconfig bridge0 192.168.0.1/24 up
    - ifconfig epair create
    - ifconfig
    - ifconfig epair0a mtu 1460
    - ifconfig epair0b mtu 1460
    - ifconfig bridge0 addm vtnet0
    - ifconfig bridge0 addm epair0a
  qjail_script:
    - ifconfig
    - qjail install
    - qjail create -n lo0 -4 127.0.0.1 jail1
    - cp jail_setting.txt /usr/local/etc/qjail.config/jail1
  script:
    - qjail list
    - qjail start jail1
    - jexec jail1 ifconfig
    - jexec jail1 sysrc ipfw_enable=YES
    - jexec jail1 'firewall_type="open"' >> /etc/rc.conf
    - jexec jail1 'firewall_script="/etc/rc.firewall"' >> /etc/rc.conf
    - jexec jail1 service ipfw start
    - jexec jail1 ipfw list
