freebsd_instance:
  image: freebsd-12-0-release-amd64

task:

  install_script:
    - pkg update
    - pkg install -y python37

  jail_script:
    - ifconfig bridge create
    - ifconfig bridge0 192.168.0.1/24 up
    - ifconfig epair create
    - mkdir -p /jails/jail1
    - cd /usr/src
    - make buildworld
    - make installworld DESTDIR=/jails/jail1
    - make distribution DESTDIR=/jails/jail1
    - mount -t devfs devfs /jails/jail1/dev
    - jail -c vnet name=jail1 host.hostname=jail1 path=/jails/jail1/ persist

  script:
    - ipfw list
    - python3.7 tests/test_ipfw.py
