freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y python37
    - sysrc firewall_enable=YES
    - netstat -an
  script:
    - python3.7 tests/test_ipfw_list.py
